---
- name: Install compiler and required packages
  become: yes
  become_user: root
  yum: name={{ item }} state=latest
  with_items:
  - make
  - gcc
  - gcc-c++
  - tar
  - bzip2
  - patch
  - openssl-devel
  - readline-devel
  - libffi-devel
  - libyaml-devel
  - zlib-devel
  - gdbm-devel
  - ncurses-devel

- name: Creates ruby-build directory
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  file: path=~/ruby-build state=directory force=yes

- name: Downloads ruby-build
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  shell: "curl -Lk {{ rbenv_targz_url }} | tar xz --strip-components 1 --directory ~/ruby-build"
  args:
    creates: ~/ruby-build/bin/ruby-build
    warn: no

- name: Compiles Ruby
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  shell: "~/ruby-build/bin/ruby-build --verbose {{ ruby_version }} {{ ruby_install_path }}"
  args:
    creates: "{{ ruby_install_path }}/bin/ruby"

- name: Adds ruby bin dir to $PATH env var
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  lineinfile: dest=~/.bashrc line="export PATH={{ ruby_install_path }}/bin:$PATH"

- name: Disable Gem docs installation by default
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  lineinfile: "dest=~/.gemrc create=yes line='gem: --no-document'"

- name: Update RubyGems
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  shell: "{{ ruby_install_path }}/bin/gem update --system"

- name: Install bundler
  become: "{{ use_unprivileged_user }}"
  become_user: "{{ unprivileged_user_name }}"
  shell: "{{ ruby_install_path }}/bin/gem install bundler"
